// flow-typed signature: e2d6c7c7953a1f98c4313a47d9e62141
// flow-typed version: <<STUB>>/abbrev_v^1.0.7/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abbrev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'abbrev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abbrev/abbrev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abbrev/abbrev.js' {
  declare module.exports: $Exports<'abbrev/abbrev'>;
}
