// flow-typed signature: a4594d4146deba02309ae13c7c915de8
// flow-typed version: <<STUB>>/express-bunyan-logger_v^1.3.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-bunyan-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-bunyan-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-bunyan-logger/test/app' {
  declare module.exports: any;
}

declare module 'express-bunyan-logger/test/bunyan.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-bunyan-logger/index' {
  declare module.exports: $Exports<'express-bunyan-logger'>;
}
declare module 'express-bunyan-logger/index.js' {
  declare module.exports: $Exports<'express-bunyan-logger'>;
}
declare module 'express-bunyan-logger/test/app.js' {
  declare module.exports: $Exports<'express-bunyan-logger/test/app'>;
}
declare module 'express-bunyan-logger/test/bunyan.test.js' {
  declare module.exports: $Exports<'express-bunyan-logger/test/bunyan.test'>;
}
