// flow-typed signature: 60f4e123e0732aa8f006d11e72bb0d06
// flow-typed version: <<STUB>>/express-simple-controllers_v^1.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-simple-controllers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-simple-controllers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-simple-controllers/dist/index' {
  declare module.exports: any;
}

declare module 'express-simple-controllers/dist/utils' {
  declare module.exports: any;
}

declare module 'express-simple-controllers/src/index' {
  declare module.exports: any;
}

declare module 'express-simple-controllers/src/utils' {
  declare module.exports: any;
}

declare module 'express-simple-controllers/test/mvc.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-simple-controllers/dist/index.js' {
  declare module.exports: $Exports<'express-simple-controllers/dist/index'>;
}
declare module 'express-simple-controllers/dist/utils.js' {
  declare module.exports: $Exports<'express-simple-controllers/dist/utils'>;
}
declare module 'express-simple-controllers/src/index.js' {
  declare module.exports: $Exports<'express-simple-controllers/src/index'>;
}
declare module 'express-simple-controllers/src/utils.js' {
  declare module.exports: $Exports<'express-simple-controllers/src/utils'>;
}
declare module 'express-simple-controllers/test/mvc.spec.js' {
  declare module.exports: $Exports<'express-simple-controllers/test/mvc.spec'>;
}
