// flow-typed signature: ea6b360e9c8504c3154181dd4a397686
// flow-typed version: <<STUB>>/match-media_v^0.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'match-media/matchMedia.addListener' {
  declare module.exports: any;
}

declare module 'match-media/matchMedia' {
  declare module.exports: any;
}

declare module 'match-media/test/lib/JSLitmus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'match-media/matchMedia.addListener.js' {
  declare module.exports: $Exports<'match-media/matchMedia.addListener'>;
}
declare module 'match-media/matchMedia.js' {
  declare module.exports: $Exports<'match-media/matchMedia'>;
}
declare module 'match-media/test/lib/JSLitmus.js' {
  declare module.exports: $Exports<'match-media/test/lib/JSLitmus'>;
}
