// flow-typed signature: 1904953dc3d375d9566b20a7aeb15d56
// flow-typed version: <<STUB>>/match-middleware_v^1.0.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'match-middleware/dist/index' {
  declare module.exports: any;
}

declare module 'match-middleware/src/index' {
  declare module.exports: any;
}

declare module 'match-middleware/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'match-middleware/dist/index.js' {
  declare module.exports: $Exports<'match-middleware/dist/index'>;
}
declare module 'match-middleware/src/index.js' {
  declare module.exports: $Exports<'match-middleware/src/index'>;
}
declare module 'match-middleware/test/index.js' {
  declare module.exports: $Exports<'match-middleware/test/index'>;
}
