// flow-typed signature: 28df05fe24ad39990c2ae1787cc31895
// flow-typed version: <<STUB>>/node-statsd_v^0.1.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-statsd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-statsd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-statsd/lib/statsd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-statsd/index' {
  declare module.exports: $Exports<'node-statsd'>;
}
declare module 'node-statsd/index.js' {
  declare module.exports: $Exports<'node-statsd'>;
}
declare module 'node-statsd/lib/statsd.js' {
  declare module.exports: $Exports<'node-statsd/lib/statsd'>;
}
