// flow-typed signature: 530078e0f53c29637396aec704c2d771
// flow-typed version: <<STUB>>/postal_v^2.0.4/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postal/lib/postal' {
  declare module.exports: any;
}

declare module 'postal/lib/postal.lodash' {
  declare module.exports: any;
}

declare module 'postal/lib/postal.lodash.min' {
  declare module.exports: any;
}

declare module 'postal/lib/postal.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postal/lib/postal.js' {
  declare module.exports: $Exports<'postal/lib/postal'>;
}
declare module 'postal/lib/postal.lodash.js' {
  declare module.exports: $Exports<'postal/lib/postal.lodash'>;
}
declare module 'postal/lib/postal.lodash.min.js' {
  declare module.exports: $Exports<'postal/lib/postal.lodash.min'>;
}
declare module 'postal/lib/postal.min.js' {
  declare module.exports: $Exports<'postal/lib/postal.min'>;
}
