// flow-typed signature: ebf105394c5d9ba1f60325072d8097a3
// flow-typed version: <<STUB>>/rizzo-next_vlatest/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rizzo-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rizzo-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rizzo-next/bin/rizzo' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/common' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/ads/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/alert/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/analytics/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/article_body/article_body' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/article_body/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/article/article_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/article/article_model' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/article/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/articles/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/author/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/avatar/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/button/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/button/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/category_list/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/food_and_drink/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/footer/footer_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/footer/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/guidebook/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/header/header_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/header/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/hotels/hotels_widget' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/hotels/hotels.events' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/hotels/hotels.tracking' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/hotels/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/image_gallery/image_gallery' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/image_gallery/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/image_slider/image_slider' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/image_slider/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/interests/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/intro_narrative/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/login/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/login/login_manager' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/login/user' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/logo/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/love_letter/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map_static/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/api' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/interactive-map' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/map_api' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/map_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/mapbox/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/mapbox/markerset' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/state' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/tab_titles' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/about-panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/about-panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/alert' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/alert' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/item' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/item' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/map' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/map' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/pin' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/pin' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-details' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-details' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-dropdown' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-dropdown' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-fetching' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar-fetching' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/sidebar' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/tab' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/map/views/tab' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/masthead/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/masthead/masthead_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/masthead/masthead_nav' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/modal/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/modal/modal_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/navigation/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/navigation/navigation_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/navigation/navigation_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/navigation/navigation_state' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/notification/notification' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/overlay/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/poi_callout/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/poi_callout/poi_callout' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/progress/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/progress/progress' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/related_guidebook/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/scroll_to/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/scroll_to/scroll-to' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_api' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_item/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_server_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/search/search_state' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/sights/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/sights/sights_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/slideshow/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/slideshow/slide_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/slideshow/slideshow' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/social_share/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/social_share/social-share' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/sticky_footer/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/sticky_footer/sticky_footer' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/sub_nav/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/survival_guide/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/svg_icons/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/tabs/tabs_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/things_to_do/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/things_to_do/things_to_do' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/tooltip/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/top_places/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/top_places/top_places_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/topic/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/tours/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/travel_alert/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/usabilla/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video_overlay/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video_overlay/video_overlay_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video_poster_button/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video_poster_button/video_poster_button_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video/brightcove' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/components/video/video_player' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/ads/ad_manager' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/ads/ad_sizes' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/ads/ad_unit' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/arkham' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/bane' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/block_checker' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/component_registry' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/component' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/cookie_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/decorators/channel' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/decorators/publish' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/decorators/subscribe' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/decorators/track' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/event_tracker' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/events/track_event' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/events/trackers/analytics' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/events/trackers/flamsteed' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/events/trackers/ga_event_map' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/logger' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/mixins/events' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/mobile_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/model' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/perf_monitor' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/rizzo_events' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/rizzo' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/shop_cookie_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/breakpoints' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/covervid' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/detect_swipe' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/fitText' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/getScrollbarWidth' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/highlight' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/is_dev' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/is_json' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/matchMedia' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/perf' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/preload' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/stringHelpers' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/core/utils/waitForTransition' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/rizzo-next' {
  declare module.exports: any;
}

declare module 'rizzo-next/dist/rizzo' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/inherited-summary' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/inner-link' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/manual' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/patch-for-local' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/prettify/prettify' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/pretty-print' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/search_index' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/search' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/js/script/test-summary' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/js/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/vendor/fuse.min' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/vendor/highlight' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/vendor/jquery.min' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/vendor/ticker' {
  declare module.exports: any;
}

declare module 'rizzo-next/docs/sass/assets/vendor/waypoints.min' {
  declare module.exports: any;
}

declare module 'rizzo-next/karma.conf' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/commands/build' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/commands/create' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/compiler' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/helpers/nav_class_names' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/methods/getDirectories' {
  declare module.exports: any;
}

declare module 'rizzo-next/lib/methods/getPartials' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/articleBody.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/articles.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/header.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/hotels.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/login_manager.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/map.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/masthead.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/navigation.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/overlay.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/search.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/slideshow.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/tabs.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/things_to_do.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/video_overlay.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/video_poster_button.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/components/video.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/core.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/core/component_registry.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/core/perf_monitor.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/core/rizzo.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/decorators/channel.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/decorators/publish.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/decorators/subscribe.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/decorators/track.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/spec/unit/util/cookie_util.spec' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/common' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/ads/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/alert/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/analytics/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/article_body/article_body' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/article_body/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/article/article_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/article/article_model' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/article/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/articles/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/author/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/avatar/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/button/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/category_list/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/food_and_drink/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/footer/footer_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/footer/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/guidebook/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/header/header_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/header/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/hotels/hotels_widget' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/hotels/hotels.events' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/hotels/hotels.tracking' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/hotels/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/image_gallery/image_gallery' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/image_gallery/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/image_slider/image_slider' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/image_slider/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/interests/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/intro_narrative/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/login/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/login/login_manager' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/login/user' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/logo/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/love_letter/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map_static/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/api' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/interactive-map' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/map_api' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/map_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/mapbox/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/mapbox/markerset' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/state' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/tab_titles' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/about-panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/alert' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/item' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/map' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/panel' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/pin' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/sidebar-details' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/sidebar-dropdown' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/sidebar-fetching' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/sidebar' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/map/views/tab' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/masthead/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/masthead/masthead_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/masthead/masthead_nav' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/modal/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/modal/modal_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/navigation/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/navigation/navigation_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/navigation/navigation_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/navigation/navigation_state' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/notification/notification' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/overlay/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/poi_callout/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/poi_callout/poi_callout' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/progress/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/progress/progress' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/related_guidebook/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/scroll_to/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/scroll_to/scroll-to' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_api' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_item/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_server_actions' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/search/search_state' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/sights/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/sights/sights_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/slideshow/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/slideshow/slide_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/slideshow/slideshow' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/social_share/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/social_share/social-share' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/sticky_footer/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/sticky_footer/sticky_footer' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/sub_nav/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/survival_guide/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/svg_icons/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/tabs/tabs_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/things_to_do/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/things_to_do/things_to_do' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/tooltip/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/top_places/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/top_places/top_places_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/topic/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/tours/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/travel_alert/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/usabilla/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video_overlay/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video_overlay/video_overlay_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video_poster_button/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video_poster_button/video_poster_button_component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video/brightcove' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video/index' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/components/video/video_player' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/ads/ad_manager' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/ads/ad_sizes' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/ads/ad_unit' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/arkham' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/bane' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/block_checker' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/component_registry' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/component' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/cookie_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/decorators/channel' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/decorators/publish' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/decorators/subscribe' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/decorators/track' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/event_tracker' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/events/track_event' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/events/trackers/analytics' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/events/trackers/flamsteed' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/events/trackers/ga_event_map' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/logger' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/main' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/mixins/events' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/mobile_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/model' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/perf_monitor' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/rizzo_events' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/rizzo' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/shop_cookie_util' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/breakpoints' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/covervid' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/detect_swipe' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/fitText' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/getScrollbarWidth' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/highlight' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/is_dev' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/is_json' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/matchMedia' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/perf' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/preload' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/stringHelpers' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/core/utils/waitForTransition' {
  declare module.exports: any;
}

declare module 'rizzo-next/src/rizzo' {
  declare module.exports: any;
}

declare module 'rizzo-next/styleguide/components/root' {
  declare module.exports: any;
}

declare module 'rizzo-next/styleguide/data' {
  declare module.exports: any;
}

declare module 'rizzo-next/webpack.config' {
  declare module.exports: any;
}

declare module 'rizzo-next/webpack.dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rizzo-next/bin/rizzo.js' {
  declare module.exports: $Exports<'rizzo-next/bin/rizzo'>;
}
declare module 'rizzo-next/dist/common.js' {
  declare module.exports: $Exports<'rizzo-next/dist/common'>;
}
declare module 'rizzo-next/dist/components/ads/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/ads/index'>;
}
declare module 'rizzo-next/dist/components/alert/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/alert/index'>;
}
declare module 'rizzo-next/dist/components/analytics/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/analytics/index'>;
}
declare module 'rizzo-next/dist/components/article_body/article_body.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/article_body/article_body'>;
}
declare module 'rizzo-next/dist/components/article_body/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/article_body/index'>;
}
declare module 'rizzo-next/dist/components/article/article_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/article/article_component'>;
}
declare module 'rizzo-next/dist/components/article/article_model.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/article/article_model'>;
}
declare module 'rizzo-next/dist/components/article/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/article/index'>;
}
declare module 'rizzo-next/dist/components/articles/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/articles/index'>;
}
declare module 'rizzo-next/dist/components/author/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/author/index'>;
}
declare module 'rizzo-next/dist/components/avatar/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/avatar/index'>;
}
declare module 'rizzo-next/dist/components/button/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/button/index'>;
}
declare module 'rizzo-next/dist/components/button/index.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/button/index'>;
}
declare module 'rizzo-next/dist/components/category_list/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/category_list/index'>;
}
declare module 'rizzo-next/dist/components/food_and_drink/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/food_and_drink/index'>;
}
declare module 'rizzo-next/dist/components/footer/footer_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/footer/footer_component'>;
}
declare module 'rizzo-next/dist/components/footer/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/footer/index'>;
}
declare module 'rizzo-next/dist/components/guidebook/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/guidebook/index'>;
}
declare module 'rizzo-next/dist/components/header/header_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/header/header_component'>;
}
declare module 'rizzo-next/dist/components/header/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/header/index'>;
}
declare module 'rizzo-next/dist/components/hotels/hotels_widget.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/hotels/hotels_widget'>;
}
declare module 'rizzo-next/dist/components/hotels/hotels.events.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/hotels/hotels.events'>;
}
declare module 'rizzo-next/dist/components/hotels/hotels.tracking.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/hotels/hotels.tracking'>;
}
declare module 'rizzo-next/dist/components/hotels/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/hotels/index'>;
}
declare module 'rizzo-next/dist/components/image_gallery/image_gallery.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/image_gallery/image_gallery'>;
}
declare module 'rizzo-next/dist/components/image_gallery/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/image_gallery/index'>;
}
declare module 'rizzo-next/dist/components/image_slider/image_slider.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/image_slider/image_slider'>;
}
declare module 'rizzo-next/dist/components/image_slider/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/image_slider/index'>;
}
declare module 'rizzo-next/dist/components/interests/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/interests/index'>;
}
declare module 'rizzo-next/dist/components/intro_narrative/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/intro_narrative/index'>;
}
declare module 'rizzo-next/dist/components/login/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/login/index'>;
}
declare module 'rizzo-next/dist/components/login/login_manager.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/login/login_manager'>;
}
declare module 'rizzo-next/dist/components/login/user.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/login/user'>;
}
declare module 'rizzo-next/dist/components/logo/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/logo/index'>;
}
declare module 'rizzo-next/dist/components/love_letter/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/love_letter/index'>;
}
declare module 'rizzo-next/dist/components/map_static/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map_static/index'>;
}
declare module 'rizzo-next/dist/components/map/actions.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/actions'>;
}
declare module 'rizzo-next/dist/components/map/api.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/api'>;
}
declare module 'rizzo-next/dist/components/map/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/index'>;
}
declare module 'rizzo-next/dist/components/map/interactive-map.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/interactive-map'>;
}
declare module 'rizzo-next/dist/components/map/map_api.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/map_api'>;
}
declare module 'rizzo-next/dist/components/map/map_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/map_component'>;
}
declare module 'rizzo-next/dist/components/map/mapbox/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/mapbox/index'>;
}
declare module 'rizzo-next/dist/components/map/mapbox/markerset.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/mapbox/markerset'>;
}
declare module 'rizzo-next/dist/components/map/state.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/state'>;
}
declare module 'rizzo-next/dist/components/map/tab_titles.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/tab_titles'>;
}
declare module 'rizzo-next/dist/components/map/views/about-panel.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/about-panel'>;
}
declare module 'rizzo-next/dist/components/map/views/about-panel.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/about-panel'>;
}
declare module 'rizzo-next/dist/components/map/views/alert.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/alert'>;
}
declare module 'rizzo-next/dist/components/map/views/alert.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/alert'>;
}
declare module 'rizzo-next/dist/components/map/views/item.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/item'>;
}
declare module 'rizzo-next/dist/components/map/views/item.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/item'>;
}
declare module 'rizzo-next/dist/components/map/views/main.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/main'>;
}
declare module 'rizzo-next/dist/components/map/views/main.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/main'>;
}
declare module 'rizzo-next/dist/components/map/views/map.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/map'>;
}
declare module 'rizzo-next/dist/components/map/views/map.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/map'>;
}
declare module 'rizzo-next/dist/components/map/views/panel.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/panel'>;
}
declare module 'rizzo-next/dist/components/map/views/panel.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/panel'>;
}
declare module 'rizzo-next/dist/components/map/views/pin.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/pin'>;
}
declare module 'rizzo-next/dist/components/map/views/pin.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/pin'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-details.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-details'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-details.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-details'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-dropdown.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-dropdown'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-dropdown.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-dropdown'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-fetching.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-fetching'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar-fetching.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar-fetching'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar'>;
}
declare module 'rizzo-next/dist/components/map/views/sidebar.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/sidebar'>;
}
declare module 'rizzo-next/dist/components/map/views/tab.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/tab'>;
}
declare module 'rizzo-next/dist/components/map/views/tab.jsx' {
  declare module.exports: $Exports<'rizzo-next/dist/components/map/views/tab'>;
}
declare module 'rizzo-next/dist/components/masthead/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/masthead/index'>;
}
declare module 'rizzo-next/dist/components/masthead/masthead_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/masthead/masthead_component'>;
}
declare module 'rizzo-next/dist/components/masthead/masthead_nav.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/masthead/masthead_nav'>;
}
declare module 'rizzo-next/dist/components/modal/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/modal/index'>;
}
declare module 'rizzo-next/dist/components/modal/modal_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/modal/modal_component'>;
}
declare module 'rizzo-next/dist/components/navigation/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/navigation/index'>;
}
declare module 'rizzo-next/dist/components/navigation/navigation_actions.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/navigation/navigation_actions'>;
}
declare module 'rizzo-next/dist/components/navigation/navigation_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/navigation/navigation_component'>;
}
declare module 'rizzo-next/dist/components/navigation/navigation_state.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/navigation/navigation_state'>;
}
declare module 'rizzo-next/dist/components/notification/notification.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/notification/notification'>;
}
declare module 'rizzo-next/dist/components/overlay/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/overlay/index'>;
}
declare module 'rizzo-next/dist/components/poi_callout/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/poi_callout/index'>;
}
declare module 'rizzo-next/dist/components/poi_callout/poi_callout.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/poi_callout/poi_callout'>;
}
declare module 'rizzo-next/dist/components/progress/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/progress/index'>;
}
declare module 'rizzo-next/dist/components/progress/progress.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/progress/progress'>;
}
declare module 'rizzo-next/dist/components/related_guidebook/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/related_guidebook/index'>;
}
declare module 'rizzo-next/dist/components/scroll_to/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/scroll_to/index'>;
}
declare module 'rizzo-next/dist/components/scroll_to/scroll-to.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/scroll_to/scroll-to'>;
}
declare module 'rizzo-next/dist/components/search/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/index'>;
}
declare module 'rizzo-next/dist/components/search/search_actions.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_actions'>;
}
declare module 'rizzo-next/dist/components/search/search_api.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_api'>;
}
declare module 'rizzo-next/dist/components/search/search_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_component'>;
}
declare module 'rizzo-next/dist/components/search/search_item/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_item/index'>;
}
declare module 'rizzo-next/dist/components/search/search_server_actions.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_server_actions'>;
}
declare module 'rizzo-next/dist/components/search/search_state.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/search/search_state'>;
}
declare module 'rizzo-next/dist/components/sights/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/sights/index'>;
}
declare module 'rizzo-next/dist/components/sights/sights_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/sights/sights_component'>;
}
declare module 'rizzo-next/dist/components/slideshow/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/slideshow/index'>;
}
declare module 'rizzo-next/dist/components/slideshow/slide_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/slideshow/slide_component'>;
}
declare module 'rizzo-next/dist/components/slideshow/slideshow.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/slideshow/slideshow'>;
}
declare module 'rizzo-next/dist/components/social_share/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/social_share/index'>;
}
declare module 'rizzo-next/dist/components/social_share/social-share.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/social_share/social-share'>;
}
declare module 'rizzo-next/dist/components/sticky_footer/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/sticky_footer/index'>;
}
declare module 'rizzo-next/dist/components/sticky_footer/sticky_footer.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/sticky_footer/sticky_footer'>;
}
declare module 'rizzo-next/dist/components/sub_nav/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/sub_nav/index'>;
}
declare module 'rizzo-next/dist/components/survival_guide/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/survival_guide/index'>;
}
declare module 'rizzo-next/dist/components/svg_icons/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/svg_icons/index'>;
}
declare module 'rizzo-next/dist/components/tabs/tabs_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/tabs/tabs_component'>;
}
declare module 'rizzo-next/dist/components/things_to_do/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/things_to_do/index'>;
}
declare module 'rizzo-next/dist/components/things_to_do/things_to_do.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/things_to_do/things_to_do'>;
}
declare module 'rizzo-next/dist/components/tooltip/main.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/tooltip/main'>;
}
declare module 'rizzo-next/dist/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/tooltip/tooltip'>;
}
declare module 'rizzo-next/dist/components/top_places/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/top_places/index'>;
}
declare module 'rizzo-next/dist/components/top_places/top_places_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/top_places/top_places_component'>;
}
declare module 'rizzo-next/dist/components/topic/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/topic/index'>;
}
declare module 'rizzo-next/dist/components/tours/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/tours/index'>;
}
declare module 'rizzo-next/dist/components/travel_alert/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/travel_alert/index'>;
}
declare module 'rizzo-next/dist/components/usabilla/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/usabilla/index'>;
}
declare module 'rizzo-next/dist/components/video_overlay/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video_overlay/index'>;
}
declare module 'rizzo-next/dist/components/video_overlay/video_overlay_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video_overlay/video_overlay_component'>;
}
declare module 'rizzo-next/dist/components/video_poster_button/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video_poster_button/index'>;
}
declare module 'rizzo-next/dist/components/video_poster_button/video_poster_button_component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video_poster_button/video_poster_button_component'>;
}
declare module 'rizzo-next/dist/components/video/brightcove.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video/brightcove'>;
}
declare module 'rizzo-next/dist/components/video/index.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video/index'>;
}
declare module 'rizzo-next/dist/components/video/video_player.js' {
  declare module.exports: $Exports<'rizzo-next/dist/components/video/video_player'>;
}
declare module 'rizzo-next/dist/core/ads/ad_manager.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/ads/ad_manager'>;
}
declare module 'rizzo-next/dist/core/ads/ad_sizes.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/ads/ad_sizes'>;
}
declare module 'rizzo-next/dist/core/ads/ad_unit.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/ads/ad_unit'>;
}
declare module 'rizzo-next/dist/core/arkham.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/arkham'>;
}
declare module 'rizzo-next/dist/core/bane.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/bane'>;
}
declare module 'rizzo-next/dist/core/block_checker.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/block_checker'>;
}
declare module 'rizzo-next/dist/core/component_registry.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/component_registry'>;
}
declare module 'rizzo-next/dist/core/component.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/component'>;
}
declare module 'rizzo-next/dist/core/cookie_util.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/cookie_util'>;
}
declare module 'rizzo-next/dist/core/decorators/channel.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/decorators/channel'>;
}
declare module 'rizzo-next/dist/core/decorators/publish.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/decorators/publish'>;
}
declare module 'rizzo-next/dist/core/decorators/subscribe.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/decorators/subscribe'>;
}
declare module 'rizzo-next/dist/core/decorators/track.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/decorators/track'>;
}
declare module 'rizzo-next/dist/core/event_tracker.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/event_tracker'>;
}
declare module 'rizzo-next/dist/core/events/track_event.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/events/track_event'>;
}
declare module 'rizzo-next/dist/core/events/trackers/analytics.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/events/trackers/analytics'>;
}
declare module 'rizzo-next/dist/core/events/trackers/flamsteed.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/events/trackers/flamsteed'>;
}
declare module 'rizzo-next/dist/core/events/trackers/ga_event_map.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/events/trackers/ga_event_map'>;
}
declare module 'rizzo-next/dist/core/logger.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/logger'>;
}
declare module 'rizzo-next/dist/core/main.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/main'>;
}
declare module 'rizzo-next/dist/core/mixins/events.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/mixins/events'>;
}
declare module 'rizzo-next/dist/core/mobile_util.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/mobile_util'>;
}
declare module 'rizzo-next/dist/core/model.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/model'>;
}
declare module 'rizzo-next/dist/core/perf_monitor.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/perf_monitor'>;
}
declare module 'rizzo-next/dist/core/rizzo_events.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/rizzo_events'>;
}
declare module 'rizzo-next/dist/core/rizzo.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/rizzo'>;
}
declare module 'rizzo-next/dist/core/shop_cookie_util.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/shop_cookie_util'>;
}
declare module 'rizzo-next/dist/core/utils/breakpoints.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/breakpoints'>;
}
declare module 'rizzo-next/dist/core/utils/covervid.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/covervid'>;
}
declare module 'rizzo-next/dist/core/utils/detect_swipe.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/detect_swipe'>;
}
declare module 'rizzo-next/dist/core/utils/fitText.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/fitText'>;
}
declare module 'rizzo-next/dist/core/utils/getScrollbarWidth.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/getScrollbarWidth'>;
}
declare module 'rizzo-next/dist/core/utils/highlight.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/highlight'>;
}
declare module 'rizzo-next/dist/core/utils/is_dev.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/is_dev'>;
}
declare module 'rizzo-next/dist/core/utils/is_json.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/is_json'>;
}
declare module 'rizzo-next/dist/core/utils/matchMedia.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/matchMedia'>;
}
declare module 'rizzo-next/dist/core/utils/perf.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/perf'>;
}
declare module 'rizzo-next/dist/core/utils/preload.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/preload'>;
}
declare module 'rizzo-next/dist/core/utils/stringHelpers.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/stringHelpers'>;
}
declare module 'rizzo-next/dist/core/utils/waitForTransition.js' {
  declare module.exports: $Exports<'rizzo-next/dist/core/utils/waitForTransition'>;
}
declare module 'rizzo-next/dist/rizzo-next.js' {
  declare module.exports: $Exports<'rizzo-next/dist/rizzo-next'>;
}
declare module 'rizzo-next/dist/rizzo.js' {
  declare module.exports: $Exports<'rizzo-next/dist/rizzo'>;
}
declare module 'rizzo-next/docs/js/script/inherited-summary.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/inherited-summary'>;
}
declare module 'rizzo-next/docs/js/script/inner-link.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/inner-link'>;
}
declare module 'rizzo-next/docs/js/script/manual.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/manual'>;
}
declare module 'rizzo-next/docs/js/script/patch-for-local.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/patch-for-local'>;
}
declare module 'rizzo-next/docs/js/script/prettify/prettify.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/prettify/prettify'>;
}
declare module 'rizzo-next/docs/js/script/pretty-print.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/pretty-print'>;
}
declare module 'rizzo-next/docs/js/script/search_index.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/search_index'>;
}
declare module 'rizzo-next/docs/js/script/search.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/search'>;
}
declare module 'rizzo-next/docs/js/script/test-summary.js' {
  declare module.exports: $Exports<'rizzo-next/docs/js/script/test-summary'>;
}
declare module 'rizzo-next/docs/sass/assets/js/main.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/js/main'>;
}
declare module 'rizzo-next/docs/sass/assets/vendor/fuse.min.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/vendor/fuse.min'>;
}
declare module 'rizzo-next/docs/sass/assets/vendor/highlight.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/vendor/highlight'>;
}
declare module 'rizzo-next/docs/sass/assets/vendor/jquery.min.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/vendor/jquery.min'>;
}
declare module 'rizzo-next/docs/sass/assets/vendor/ticker.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/vendor/ticker'>;
}
declare module 'rizzo-next/docs/sass/assets/vendor/waypoints.min.js' {
  declare module.exports: $Exports<'rizzo-next/docs/sass/assets/vendor/waypoints.min'>;
}
declare module 'rizzo-next/karma.conf.js' {
  declare module.exports: $Exports<'rizzo-next/karma.conf'>;
}
declare module 'rizzo-next/lib/commands/build.js' {
  declare module.exports: $Exports<'rizzo-next/lib/commands/build'>;
}
declare module 'rizzo-next/lib/commands/create.js' {
  declare module.exports: $Exports<'rizzo-next/lib/commands/create'>;
}
declare module 'rizzo-next/lib/compiler.js' {
  declare module.exports: $Exports<'rizzo-next/lib/compiler'>;
}
declare module 'rizzo-next/lib/helpers/nav_class_names.js' {
  declare module.exports: $Exports<'rizzo-next/lib/helpers/nav_class_names'>;
}
declare module 'rizzo-next/lib/methods/getDirectories.js' {
  declare module.exports: $Exports<'rizzo-next/lib/methods/getDirectories'>;
}
declare module 'rizzo-next/lib/methods/getPartials.js' {
  declare module.exports: $Exports<'rizzo-next/lib/methods/getPartials'>;
}
declare module 'rizzo-next/spec/index.js' {
  declare module.exports: $Exports<'rizzo-next/spec/index'>;
}
declare module 'rizzo-next/spec/unit/components/articleBody.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/articleBody.spec'>;
}
declare module 'rizzo-next/spec/unit/components/articles.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/articles.spec'>;
}
declare module 'rizzo-next/spec/unit/components/header.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/header.spec'>;
}
declare module 'rizzo-next/spec/unit/components/hotels.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/hotels.spec'>;
}
declare module 'rizzo-next/spec/unit/components/login_manager.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/login_manager.spec'>;
}
declare module 'rizzo-next/spec/unit/components/map.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/map.spec'>;
}
declare module 'rizzo-next/spec/unit/components/masthead.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/masthead.spec'>;
}
declare module 'rizzo-next/spec/unit/components/navigation.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/navigation.spec'>;
}
declare module 'rizzo-next/spec/unit/components/overlay.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/overlay.spec'>;
}
declare module 'rizzo-next/spec/unit/components/search.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/search.spec'>;
}
declare module 'rizzo-next/spec/unit/components/slideshow.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/slideshow.spec'>;
}
declare module 'rizzo-next/spec/unit/components/tabs.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/tabs.spec'>;
}
declare module 'rizzo-next/spec/unit/components/things_to_do.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/things_to_do.spec'>;
}
declare module 'rizzo-next/spec/unit/components/video_overlay.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/video_overlay.spec'>;
}
declare module 'rizzo-next/spec/unit/components/video_poster_button.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/video_poster_button.spec'>;
}
declare module 'rizzo-next/spec/unit/components/video.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/components/video.spec'>;
}
declare module 'rizzo-next/spec/unit/core.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/core.spec'>;
}
declare module 'rizzo-next/spec/unit/core/component_registry.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/core/component_registry.spec'>;
}
declare module 'rizzo-next/spec/unit/core/perf_monitor.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/core/perf_monitor.spec'>;
}
declare module 'rizzo-next/spec/unit/core/rizzo.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/core/rizzo.spec'>;
}
declare module 'rizzo-next/spec/unit/decorators/channel.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/decorators/channel.spec'>;
}
declare module 'rizzo-next/spec/unit/decorators/publish.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/decorators/publish.spec'>;
}
declare module 'rizzo-next/spec/unit/decorators/subscribe.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/decorators/subscribe.spec'>;
}
declare module 'rizzo-next/spec/unit/decorators/track.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/decorators/track.spec'>;
}
declare module 'rizzo-next/spec/unit/util/cookie_util.spec.js' {
  declare module.exports: $Exports<'rizzo-next/spec/unit/util/cookie_util.spec'>;
}
declare module 'rizzo-next/src/common.js' {
  declare module.exports: $Exports<'rizzo-next/src/common'>;
}
declare module 'rizzo-next/src/components/ads/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/ads/index'>;
}
declare module 'rizzo-next/src/components/alert/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/alert/index'>;
}
declare module 'rizzo-next/src/components/analytics/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/analytics/index'>;
}
declare module 'rizzo-next/src/components/article_body/article_body.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/article_body/article_body'>;
}
declare module 'rizzo-next/src/components/article_body/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/article_body/index'>;
}
declare module 'rizzo-next/src/components/article/article_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/article/article_component'>;
}
declare module 'rizzo-next/src/components/article/article_model.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/article/article_model'>;
}
declare module 'rizzo-next/src/components/article/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/article/index'>;
}
declare module 'rizzo-next/src/components/articles/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/articles/index'>;
}
declare module 'rizzo-next/src/components/author/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/author/index'>;
}
declare module 'rizzo-next/src/components/avatar/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/avatar/index'>;
}
declare module 'rizzo-next/src/components/button/index.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/button/index'>;
}
declare module 'rizzo-next/src/components/category_list/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/category_list/index'>;
}
declare module 'rizzo-next/src/components/food_and_drink/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/food_and_drink/index'>;
}
declare module 'rizzo-next/src/components/footer/footer_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/footer/footer_component'>;
}
declare module 'rizzo-next/src/components/footer/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/footer/index'>;
}
declare module 'rizzo-next/src/components/guidebook/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/guidebook/index'>;
}
declare module 'rizzo-next/src/components/header/header_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/header/header_component'>;
}
declare module 'rizzo-next/src/components/header/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/header/index'>;
}
declare module 'rizzo-next/src/components/hotels/hotels_widget.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/hotels/hotels_widget'>;
}
declare module 'rizzo-next/src/components/hotels/hotels.events.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/hotels/hotels.events'>;
}
declare module 'rizzo-next/src/components/hotels/hotels.tracking.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/hotels/hotels.tracking'>;
}
declare module 'rizzo-next/src/components/hotels/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/hotels/index'>;
}
declare module 'rizzo-next/src/components/image_gallery/image_gallery.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/image_gallery/image_gallery'>;
}
declare module 'rizzo-next/src/components/image_gallery/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/image_gallery/index'>;
}
declare module 'rizzo-next/src/components/image_slider/image_slider.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/image_slider/image_slider'>;
}
declare module 'rizzo-next/src/components/image_slider/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/image_slider/index'>;
}
declare module 'rizzo-next/src/components/interests/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/interests/index'>;
}
declare module 'rizzo-next/src/components/intro_narrative/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/intro_narrative/index'>;
}
declare module 'rizzo-next/src/components/login/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/login/index'>;
}
declare module 'rizzo-next/src/components/login/login_manager.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/login/login_manager'>;
}
declare module 'rizzo-next/src/components/login/user.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/login/user'>;
}
declare module 'rizzo-next/src/components/logo/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/logo/index'>;
}
declare module 'rizzo-next/src/components/love_letter/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/love_letter/index'>;
}
declare module 'rizzo-next/src/components/map_static/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map_static/index'>;
}
declare module 'rizzo-next/src/components/map/actions.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/actions'>;
}
declare module 'rizzo-next/src/components/map/api.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/api'>;
}
declare module 'rizzo-next/src/components/map/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/index'>;
}
declare module 'rizzo-next/src/components/map/interactive-map.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/interactive-map'>;
}
declare module 'rizzo-next/src/components/map/map_api.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/map_api'>;
}
declare module 'rizzo-next/src/components/map/map_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/map_component'>;
}
declare module 'rizzo-next/src/components/map/mapbox/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/mapbox/index'>;
}
declare module 'rizzo-next/src/components/map/mapbox/markerset.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/mapbox/markerset'>;
}
declare module 'rizzo-next/src/components/map/state.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/state'>;
}
declare module 'rizzo-next/src/components/map/tab_titles.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/tab_titles'>;
}
declare module 'rizzo-next/src/components/map/views/about-panel.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/about-panel'>;
}
declare module 'rizzo-next/src/components/map/views/alert.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/alert'>;
}
declare module 'rizzo-next/src/components/map/views/item.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/item'>;
}
declare module 'rizzo-next/src/components/map/views/main.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/main'>;
}
declare module 'rizzo-next/src/components/map/views/map.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/map'>;
}
declare module 'rizzo-next/src/components/map/views/panel.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/panel'>;
}
declare module 'rizzo-next/src/components/map/views/pin.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/pin'>;
}
declare module 'rizzo-next/src/components/map/views/sidebar-details.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/sidebar-details'>;
}
declare module 'rizzo-next/src/components/map/views/sidebar-dropdown.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/sidebar-dropdown'>;
}
declare module 'rizzo-next/src/components/map/views/sidebar-fetching.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/sidebar-fetching'>;
}
declare module 'rizzo-next/src/components/map/views/sidebar.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/sidebar'>;
}
declare module 'rizzo-next/src/components/map/views/tab.jsx' {
  declare module.exports: $Exports<'rizzo-next/src/components/map/views/tab'>;
}
declare module 'rizzo-next/src/components/masthead/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/masthead/index'>;
}
declare module 'rizzo-next/src/components/masthead/masthead_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/masthead/masthead_component'>;
}
declare module 'rizzo-next/src/components/masthead/masthead_nav.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/masthead/masthead_nav'>;
}
declare module 'rizzo-next/src/components/modal/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/modal/index'>;
}
declare module 'rizzo-next/src/components/modal/modal_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/modal/modal_component'>;
}
declare module 'rizzo-next/src/components/navigation/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/navigation/index'>;
}
declare module 'rizzo-next/src/components/navigation/navigation_actions.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/navigation/navigation_actions'>;
}
declare module 'rizzo-next/src/components/navigation/navigation_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/navigation/navigation_component'>;
}
declare module 'rizzo-next/src/components/navigation/navigation_state.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/navigation/navigation_state'>;
}
declare module 'rizzo-next/src/components/notification/notification.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/notification/notification'>;
}
declare module 'rizzo-next/src/components/overlay/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/overlay/index'>;
}
declare module 'rizzo-next/src/components/poi_callout/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/poi_callout/index'>;
}
declare module 'rizzo-next/src/components/poi_callout/poi_callout.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/poi_callout/poi_callout'>;
}
declare module 'rizzo-next/src/components/progress/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/progress/index'>;
}
declare module 'rizzo-next/src/components/progress/progress.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/progress/progress'>;
}
declare module 'rizzo-next/src/components/related_guidebook/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/related_guidebook/index'>;
}
declare module 'rizzo-next/src/components/scroll_to/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/scroll_to/index'>;
}
declare module 'rizzo-next/src/components/scroll_to/scroll-to.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/scroll_to/scroll-to'>;
}
declare module 'rizzo-next/src/components/search/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/index'>;
}
declare module 'rizzo-next/src/components/search/search_actions.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_actions'>;
}
declare module 'rizzo-next/src/components/search/search_api.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_api'>;
}
declare module 'rizzo-next/src/components/search/search_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_component'>;
}
declare module 'rizzo-next/src/components/search/search_item/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_item/index'>;
}
declare module 'rizzo-next/src/components/search/search_server_actions.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_server_actions'>;
}
declare module 'rizzo-next/src/components/search/search_state.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/search/search_state'>;
}
declare module 'rizzo-next/src/components/sights/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/sights/index'>;
}
declare module 'rizzo-next/src/components/sights/sights_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/sights/sights_component'>;
}
declare module 'rizzo-next/src/components/slideshow/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/slideshow/index'>;
}
declare module 'rizzo-next/src/components/slideshow/slide_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/slideshow/slide_component'>;
}
declare module 'rizzo-next/src/components/slideshow/slideshow.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/slideshow/slideshow'>;
}
declare module 'rizzo-next/src/components/social_share/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/social_share/index'>;
}
declare module 'rizzo-next/src/components/social_share/social-share.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/social_share/social-share'>;
}
declare module 'rizzo-next/src/components/sticky_footer/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/sticky_footer/index'>;
}
declare module 'rizzo-next/src/components/sticky_footer/sticky_footer.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/sticky_footer/sticky_footer'>;
}
declare module 'rizzo-next/src/components/sub_nav/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/sub_nav/index'>;
}
declare module 'rizzo-next/src/components/survival_guide/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/survival_guide/index'>;
}
declare module 'rizzo-next/src/components/svg_icons/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/svg_icons/index'>;
}
declare module 'rizzo-next/src/components/tabs/tabs_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/tabs/tabs_component'>;
}
declare module 'rizzo-next/src/components/things_to_do/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/things_to_do/index'>;
}
declare module 'rizzo-next/src/components/things_to_do/things_to_do.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/things_to_do/things_to_do'>;
}
declare module 'rizzo-next/src/components/tooltip/main.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/tooltip/main'>;
}
declare module 'rizzo-next/src/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/tooltip/tooltip'>;
}
declare module 'rizzo-next/src/components/top_places/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/top_places/index'>;
}
declare module 'rizzo-next/src/components/top_places/top_places_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/top_places/top_places_component'>;
}
declare module 'rizzo-next/src/components/topic/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/topic/index'>;
}
declare module 'rizzo-next/src/components/tours/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/tours/index'>;
}
declare module 'rizzo-next/src/components/travel_alert/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/travel_alert/index'>;
}
declare module 'rizzo-next/src/components/usabilla/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/usabilla/index'>;
}
declare module 'rizzo-next/src/components/video_overlay/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video_overlay/index'>;
}
declare module 'rizzo-next/src/components/video_overlay/video_overlay_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video_overlay/video_overlay_component'>;
}
declare module 'rizzo-next/src/components/video_poster_button/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video_poster_button/index'>;
}
declare module 'rizzo-next/src/components/video_poster_button/video_poster_button_component.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video_poster_button/video_poster_button_component'>;
}
declare module 'rizzo-next/src/components/video/brightcove.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video/brightcove'>;
}
declare module 'rizzo-next/src/components/video/index.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video/index'>;
}
declare module 'rizzo-next/src/components/video/video_player.js' {
  declare module.exports: $Exports<'rizzo-next/src/components/video/video_player'>;
}
declare module 'rizzo-next/src/core/ads/ad_manager.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/ads/ad_manager'>;
}
declare module 'rizzo-next/src/core/ads/ad_sizes.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/ads/ad_sizes'>;
}
declare module 'rizzo-next/src/core/ads/ad_unit.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/ads/ad_unit'>;
}
declare module 'rizzo-next/src/core/arkham.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/arkham'>;
}
declare module 'rizzo-next/src/core/bane.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/bane'>;
}
declare module 'rizzo-next/src/core/block_checker.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/block_checker'>;
}
declare module 'rizzo-next/src/core/component_registry.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/component_registry'>;
}
declare module 'rizzo-next/src/core/component.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/component'>;
}
declare module 'rizzo-next/src/core/cookie_util.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/cookie_util'>;
}
declare module 'rizzo-next/src/core/decorators/channel.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/decorators/channel'>;
}
declare module 'rizzo-next/src/core/decorators/publish.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/decorators/publish'>;
}
declare module 'rizzo-next/src/core/decorators/subscribe.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/decorators/subscribe'>;
}
declare module 'rizzo-next/src/core/decorators/track.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/decorators/track'>;
}
declare module 'rizzo-next/src/core/event_tracker.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/event_tracker'>;
}
declare module 'rizzo-next/src/core/events/track_event.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/events/track_event'>;
}
declare module 'rizzo-next/src/core/events/trackers/analytics.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/events/trackers/analytics'>;
}
declare module 'rizzo-next/src/core/events/trackers/flamsteed.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/events/trackers/flamsteed'>;
}
declare module 'rizzo-next/src/core/events/trackers/ga_event_map.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/events/trackers/ga_event_map'>;
}
declare module 'rizzo-next/src/core/logger.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/logger'>;
}
declare module 'rizzo-next/src/core/main.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/main'>;
}
declare module 'rizzo-next/src/core/mixins/events.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/mixins/events'>;
}
declare module 'rizzo-next/src/core/mobile_util.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/mobile_util'>;
}
declare module 'rizzo-next/src/core/model.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/model'>;
}
declare module 'rizzo-next/src/core/perf_monitor.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/perf_monitor'>;
}
declare module 'rizzo-next/src/core/rizzo_events.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/rizzo_events'>;
}
declare module 'rizzo-next/src/core/rizzo.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/rizzo'>;
}
declare module 'rizzo-next/src/core/shop_cookie_util.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/shop_cookie_util'>;
}
declare module 'rizzo-next/src/core/utils/breakpoints.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/breakpoints'>;
}
declare module 'rizzo-next/src/core/utils/covervid.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/covervid'>;
}
declare module 'rizzo-next/src/core/utils/detect_swipe.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/detect_swipe'>;
}
declare module 'rizzo-next/src/core/utils/fitText.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/fitText'>;
}
declare module 'rizzo-next/src/core/utils/getScrollbarWidth.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/getScrollbarWidth'>;
}
declare module 'rizzo-next/src/core/utils/highlight.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/highlight'>;
}
declare module 'rizzo-next/src/core/utils/is_dev.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/is_dev'>;
}
declare module 'rizzo-next/src/core/utils/is_json.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/is_json'>;
}
declare module 'rizzo-next/src/core/utils/matchMedia.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/matchMedia'>;
}
declare module 'rizzo-next/src/core/utils/perf.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/perf'>;
}
declare module 'rizzo-next/src/core/utils/preload.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/preload'>;
}
declare module 'rizzo-next/src/core/utils/stringHelpers.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/stringHelpers'>;
}
declare module 'rizzo-next/src/core/utils/waitForTransition.js' {
  declare module.exports: $Exports<'rizzo-next/src/core/utils/waitForTransition'>;
}
declare module 'rizzo-next/src/rizzo.js' {
  declare module.exports: $Exports<'rizzo-next/src/rizzo'>;
}
declare module 'rizzo-next/styleguide/components/root.jsx' {
  declare module.exports: $Exports<'rizzo-next/styleguide/components/root'>;
}
declare module 'rizzo-next/styleguide/data.js' {
  declare module.exports: $Exports<'rizzo-next/styleguide/data'>;
}
declare module 'rizzo-next/webpack.config.js' {
  declare module.exports: $Exports<'rizzo-next/webpack.config'>;
}
declare module 'rizzo-next/webpack.dist.js' {
  declare module.exports: $Exports<'rizzo-next/webpack.dist'>;
}
