// flow-typed signature: 6edf78b5b5b1dd9b26485b04916073cd
// flow-typed version: <<STUB>>/trackjs_v^2.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trackjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'trackjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trackjs/tracker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trackjs/tracker.js' {
  declare module.exports: $Exports<'trackjs/tracker'>;
}
